### ISSUE TITLE
what is the unit of sess.run result?

### ISSUE THREAD

**Issue by kiitosu** [mattpoggi/pydnet#10]
I'd like to know with what unit is the output of sess.run.
Is that a meter? 

Or, in webcam.py there is a code below
`disp_color = applyColorMap(disp[0,:,:,0]*20, 'plasma')`
Is that mean the unit of output of sess.run (disp_color) is 20.0 meter?

If so, output of sess.run is 0-1.0 therefore max inferable range is 20.0?

**Comment by mattpoggi** [comment]
Hello @kiitosu,
the output is inverse depth in range (0-0.3), normalized according to image width. The 20. factor is for visualization purpose only. To obtain depth, you are supposed to take your disp output and use the following formula:

depth = (baseline * focal) / (disp*width)

**Comment by kiitosu** [comment]
Hello @mattpoggi ,
Thank you very much for your quick reply!
And, sorry for my poor understanding. Could I confirm details about parameters?
- What is the baseline more specifically?
- Is focal meaning "focal length" is it?
- What is the disp more specifically?
- Is width meaning "resolution of picture width" is it?

**Comment by mattpoggi** [comment]
The network is trained using stereo pairs. From stereo pairs, you can estimate a disparity map (i.e., for each pixel you can compute its horizontal displacement on the two images) that can be converted to depth by knowing the focal length and the baseline, that is the distance between the two cameras.
So the network learns this disparity representation. To answer your questions:

- the baseline is the distance between the two cameras (for KITTI dataset, 0.54 meters)
- the focal is the focal length (for KITTI, about 720 pixels)
- disp is the output of the network in form of disparities
- width is the image width in pixels

**Comment by kiitosu** [comment]
Thank you for your kind explanation!
Now I understand!
