### ISSUE TITLE
How to increase speed with GPU and Tensorflow 2?

### ISSUE THREAD

**Issue by Christoph9402** [mattpoggi/pydnet#21]
Hello, I am trying to run PyDNet on a video and it works, but the framerate is very low (around 5fps). Since I want to implement the depth estimation in an existing script, in which I already use Tensorflow 2.4.1, I adjusted the PyDnet files until it runs (basicly just adding "tf.compat.v1." whenever there is an error). How can I make sure, that my GPU is used when running the model? At the moment, only my CPU is used (55%) and my GPU is not (5%), when running the script. I was hoping to already make use of the GPU by switching to Tensorflow 2, but that is not the case.

**Comment by mattpoggi** [comment]
Hi, 
if you are using the webcam script, remove the `os.environ['CUDA_VISIBLE_DEVICES'] = '-1'` line

**Comment by Christoph9402** [comment]
Thank you for the answer, but that did not solve the problem. It turned out, that a .dll file for cuda 11 was not named properly. After renaming, the GPU is now used and it runs a little bit faster.

**Comment by shsur-27** [comment]
Hey @Christoph9402  Can you share the code ? i also want to run this model for video and my code is also not using any GPU. Can you please help me ?

**Comment by yerongguang** [comment]
Hey @Christoph9402 Can you share the code ? i also want to run this model for video and my code is also not using any GPU. Can you please help me too?
