### ISSUE TITLE
How can I obtain disparity in range [0,255]?

### ISSUE THREAD

**Issue by LulaSan** [mattpoggi/pydnet#23]
Starting from the output disp that I have read is in range [0,0.3], how can I obtain correctly the value in 0,255 range?

**Comment by shsur-27** [comment]
hey @LulaSan @mattpoggi  CAN YOU EXPLAIN ME WHAT IS H, Q , E IN BELOW LINE ?

'resolution [1:H, 2:Q, 3:E]'

**Comment by LulaSan** [comment]
Different level of resolution, from the highest 1 to the lowest E

**Comment by shsur-27** [comment]
thankyou for answering. @LulaSan  i have one more dought Actually, i want to train this model but my training is running on cpu only , i have gpu enabled but model is not using it do you have any idea about this ?
