### ISSUE TITLE
The difference  between pydnet v2 code and webtest

### ISSUE THREAD

**Issue by wanglids** [mattpoggi/pydnet#27]
When I try to test pydnetv2 code with a camera, but the result is really poor. While I capture a image to test in the web https://filippoaleotti.github.io/demo_live/run/,  the result is nice. Are there difference between them in detail? Where shoul I to get the better code?

![pydnetv2](https://user-images.githubusercontent.com/94187785/179715772-9463b835-daa7-4f61-a595-0108a06b3d89.png)
![web test](https://user-images.githubusercontent.com/94187785/179715799-dc931e13-46be-4ca1-a246-2411e5067e52.png)

**Comment by mattpoggi** [comment]
Hi @Ldqauther,
pydnetv2 has been trained on KITTI as we did for pydnet. The pydnet version in the web demo has been trained on a much more variegate dataset (https://arxiv.org/abs/2006.05724)

**Comment by wanglids** [comment]
thanks for you help!
