### ISSUE TITLE
Some problems of running pydnet

### ISSUE THREAD

**Issue by bcalbe** [mattpoggi/pydnet#3]
Dear. mattpoggi

I am a beginner in machine learning and deep learning. I had some trouble running pydnet on pycharm.
When I run webcam.py, an error 'name 'disp_color' is not defined'.The 'disp_color' is used in line 80. I'm trying to fixed this error, but I didn't make it. Hope you can give me some help. Thank you!

Best regards

**Comment by mattpoggi** [comment]
There was a typo at line 79, now it should be fixed. Thanks for reporting this
