### ISSUE TITLE
compatibility with other devices

### ISSUE THREAD

**Issue by mkaskov** [mattpoggi/pydnet#4]
What devices are you talking about?

https://github.com/mattpoggi/pydnet/blob/master/pydnet.py#L127
`disp6 = conv2d_leaky(disp5, [3, 3, disp5.shape[3], 8], [8], 1, False) # 8 channels for compatibility with @other@ devices`

**Comment by saetlan** [comment]
I'm currently also looking for this answer. By using the right number of channels, there would be no need to slice in the get_disp function.

**Comment by mattpoggi** [comment]
Dear @mkaskov and @saetlan ,
this design supported specific architectures on which we had a minimum number of channels supported by conv layer implementations (8 in this case), as in the case of some embedded devices. I can't reveal more details :)
