### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by Aaashish11** [mattpoggi/pydnet#8]
Thanks! It is working fine now, after converting width/2 to width//2 as it returned a float value and required was int.

-We wish to apply this concept into android, any guidance for the same will be appreciable! :)

**Comment by mattpoggi** [comment]
We have a working demo for Android, we plan to release it in the future

**Comment by Aaashish11** [comment]
Thanks for replying superFast!
But need to learn that thing very soon as the project deadline is around the corner! 
Can we connect better?

**Comment by mattpoggi** [comment]
You have to freeze the graph, then you can just plug it into a standard tensorflow app for android.
I'm sorry, but I'm not the guy who did this in our team and both of us are extremely busy until march 22.

**Comment by Aaashish11** [comment]
![IMG_20190315_141051](https://user-images.githubusercontent.com/42603591/54419109-a4c4ba00-472c-11e9-82ab-95423a76b516.jpg)

We require the output nodes at line no. 10, Please help with the same!

**Comment by mattpoggi** [comment]
Input and output node names are respectively "im0" and "model/resize_images_2/ResizeBilinear". If these do not work, append ":0" to both.
Good luck

**Comment by vanaja-penumatsa-dev** [comment]
Hi,
 "im0" and "model/resize_images_2/ResizeBilinear". These names are not working with current checkpoint.
